### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by atz**
Primary purpose: update underlying blacklight-spotlight gem.  Also updated solr_wrapper, a minor piece of rspec configuration, and a Devise invocation (that triggered a Deprecation warning).

### CODE REVIEW

**Comment by atz** [comment]
@bess Let me know if this is missing anything.

**Comment by cbeer** [comment]
I think we also want all the fixes we've made in exhibits too: https://github.com/sul-dlss/exhibits/commits/master

**Comment by atz** [comment]
My instructions were that all the _required_ fixes were not at the application level.  I can give it a go, but am just as happy to punt if they are not explicitly necessary now.

**Comment by atz** [comment]
@cbeer added newrelic and slowpoke.  Unclear which, if any, of the other commits you linked are applicable.  Some types of configuration adjusted don't exist here.

**Comment by atz** [comment]
Adding a cap file for staging deploy.  Need a shared_configs branch to go with it.

**Pull request merged**
